using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class MovePlate : MonoBehaviour
{
public GameObject controller;

GameObject reference = null;

<<<<<<< HEAD
<<<<<<< HEAD
// ì´ë™ ì¢Œí‘œ
public int matrixX;
public int matrixY;

// false = ì´ë™, true = ê³µê²©
public bool attack = false;
=======
=======
>>>>>>> parent of 5e7441a (ë‚˜ì´íŠ¸ ëŒ€ì²´ ì¹´ë©œ, í°ì˜ ìµœì´ˆ ì´ë™ì‹œ ë‘ì¹¸ì´ë™ êµ¬í˜„)
    //Ã¼½ºÆÇ Æ÷Áö¼Ç
    int matrixX;
    int matrixY;

    //false = ÀÌµ¿, true = °ø°İ
    public bool attack = false;
>>>>>>> parent of 5e7441a (ë‚˜ì´íŠ¸ ëŒ€ì²´ ì¹´ë©œ, í°ì˜ ìµœì´ˆ ì´ë™ì‹œ ë‘ì¹¸ì´ë™ êµ¬í˜„)

public void Start()
{
    if (attack)
    {
        gameObject.GetComponent<SpriteRenderer>().color = new Color(1.0f, 0.0f, 0.0f, 1.0f);
    }
}

public void OnMouseUp()
{
    controller = GameObject.FindGameObjectWithTag("GameController");

    if (attack)
    {
        GameObject cp = controller.GetComponent<Game>().GetPosition(matrixX, matrixY);

        Destroy(cp);

         if (cp.name == "white_king")
    {
        controller.GetComponent<Game>().Winner("Black"); // í‘ ìŠ¹ë¦¬ ì²˜ë¦¬
    }
    else if (cp.name == "black_king")
    {
        controller.GetComponent<Game>().Winner("White"); // ë°± ìŠ¹ë¦¬ ì²˜ë¦¬
    }
    }

    controller.GetComponent<Game>().SetPositionEmpty(reference.GetComponent<Chessman>().GetXBoard(),
        reference.GetComponent<Chessman>().GetYBoard());

    reference.GetComponent<Chessman>().SetXBoard(matrixX);
    reference.GetComponent<Chessman>().SetYBoard(matrixY);
    reference.GetComponent<Chessman>().SetCoords();

    controller.GetComponent<Game>().SetPosition(reference);

    controller.GetComponent<Game>().NextTurn();

    reference.GetComponent<Chessman>().DestroyMovePlates();
}

public void SetCoords(int x, int y)
{
    matrixX = x;
    matrixY = y;
}

public void SetReference(GameObject obj)
{
    reference = obj;
}

public GameObject GetReference()
{
    return reference;
}

// ëœë¤ìœ¼ë¡œ ì´ë™ ê²½ë¡œë¥¼ ì„ íƒí•˜ì—¬ ì´ë™
public void ExecuteRandomMove()
{
    GameObject[] movePlates = GameObject.FindGameObjectsWithTag("MovePlate");
    if (movePlates.Length > 0)
    {
<<<<<<< HEAD
        int index = Random.Range(0, movePlates.Length);
        movePlates[index].GetComponent<MovePlate>().OnMouseUp();
=======
        controller = GameObject.FindGameObjectWithTag("GameController");

        if (attack)
        {
            GameObject cp = controller.GetComponent<Game>().GetPosition(matrixX, matrixY);

            Destroy(cp);
        }

        controller.GetComponent<Game>().SetPositionEmpty(reference.GetComponent<Chessman>().GetXBoard(),
            reference.GetComponent<Chessman>().GetYBoard());

        reference.GetComponent<Chessman>().SetXBoard(matrixX);
        reference.GetComponent<Chessman>().SetYBoard(matrixY);
        reference.GetComponent<Chessman>().SetCoords();

        controller.GetComponent<Game>().SetPosition(reference);

        reference.GetComponent<Chessman>().DestroyMovePlates();
    }

    public void SetCoords(int x, int y)
    {
        matrixX = x;
        matrixY = y;
    }

    public void SetReference(GameObject obj)
    {
        reference = obj;
    }

    public GameObject GetReference()
    {
        return reference;
>>>>>>> parent of 5e7441a (ë‚˜ì´íŠ¸ ëŒ€ì²´ ì¹´ë©œ, í°ì˜ ìµœì´ˆ ì´ë™ì‹œ ë‘ì¹¸ì´ë™ êµ¬í˜„)
    }
}
}